site_name: INNOVACIÓN
site_url: https://ymorgil.github.io/innovacion/

theme:
   name: material
   language: es
   # logo: assets/favicon.svg
   palette:
      - scheme: default
        primary: green
        accent: indigo
        toggle:
           icon: material/toggle-switch-off-outline
           name: Modo oscuro
      - scheme: slate
        primary: pink
        accent: green
        toggle:
           icon: material/toggle-switch
           name: Modo claro
nav:
   - Inicio: index.md
   - Ateca:
        - OBS: ateca/obs.md

plugins:
   - glightbox

extra_css:
   - assets/css/extra.css

markdown_extensions:
   - attr_list
