site_name: INNOVACIÓN
site_url: https://ymorgil.github.io/innovacion/

theme:
   name: material
   language: es
   # logo: assets/favicon.svg
   palette:
      - scheme: default
        primary: green
        accent: indigo
        toggle:
           icon: material/toggle-switch-off-outline
           name: Modo oscuro
      - scheme: slate
        primary: pink
        accent: green
        toggle:
           icon: material/toggle-switch
           name: Modo claro
nav:
   - Inicio: index.md
   - Ateca:
        - Realidad Virtual y Aumentada: ateca/01-realidad-virtual-aumentada.md
        - Diseño y Fabricación 3D: ateca/02-diseno-fabricacion-3d.md
        - Repositorios de diseños 3D gratuitos: ateca/repositorios-diseños-3d-gratuitos.md
        - Radio y Audio: ateca/03-radio-audio.md
        - Vídeo y Streaming: ateca/04-video-streaming.md
        - OBS Studio: ateca/obs.md
        - Edición de Imagen e Impresión: ateca/05-edicion-imagen-impresion.md
        - Domótica y Automatización: ateca/06-domotica-automatizacion.md
        - Comparativa de webs de Aulas ATECA: ateca/comparativa-webs-ateca.md
        - Plan de mejora de la web ATECA: ateca/plan-mejora-web-ateca.md
   - Proyectos educativos:
        - Normativa Proyectos de Innovación FP: proy-educ/normativa-proyectos-innovacion.md
   - Trámites:
        - Certificado Digital: tramites/certificado-digital.md
   - Otras convocatorias:
        - Otras convocatorias y fechas: proy-otros/otras-convocatorias.md

plugins:
   - glightbox

extra_css:
   - assets/css/extra.css

markdown_extensions:
   - attr_list
   - tables
